### ISSUE TITLE
How do I disable max rpm haptic

### ISSUE THREAD

**Issue by ecwskier** [cercata/pysim2bhap#1]
I’m using the da20 in MSFS and it’s pulling the max rpm from telemetry so it ignore my input. I don’t like the vibrations for rpm as the plane runs at a high rpm most the time.

**Comment by cercata** [comment]
With version 0.8.1, if you put RPM Threshold to 100% or bigger, RPMs will be anulated.

BTW, yes, in MSFS from telemetry i get the % of RPM, so max rpm from the gui gets ignored.

**Comment by ecwskier** [comment]
Thank you for the update and quick reply. Also just want to say sim2hap is an awesome piece of software and it works really well and it was super easy to setup.

**Comment by cercata** [comment]
Happy to now you are enjoying it, thanks for the compliments
