### ISSUE TITLE
Add DCS tactile feedback for Bhaptics Glove

### ISSUE THREAD

**Issue by techdr1ve** [cercata/pysim2bhap#3]
I posted about adding tacticle feedback for DCS for the bhaptic gloves on Bhaptic discord. I ultimately think you will be the one who can do it. We have hand tracking with quest 3, if we had a bhaptic glove with finger haptic feedback ... This would make a world of difference! If not ... If I bought a DK2 kit and bhaptic gloves ... Can you give me a scope of how hard would this be to do it? Or would it be very difficult? I figure you already have all the software for the reat, maybe it would be relatively easy? Thanks!

https://discord.com/channels/724544309214445599/1235659266136739960

**Comment by cercata** [comment]
Would be nice, If I had the gloves for testing.
